name = "TurnTable"
uuid = "23926bd0-a9c5-11e8-29c2-8feb2a72d1d8"
authors = ["Lixun <lixun.xia@outlook.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
